---
### GitLab用サービス起動管理タスク
### 本ファイルは、サービス起動状態を管理する。

- name: "サービス起動状態 ( {{ item.name }} )"
  systemd:
    name: "{{ item.name }}.service"
    state: "{{ item.state }}"
    enabled: "{{ item.enabled }}"
  when: ansible_distribution_major_version >= "7"
  with_items: "{{ gitlab_services }}"
