- name: "restart httpd"
  systemd:
    name: httpd.service
    state: restarted
  when: ansible_distribution_major_version == "7" or ansible_distribution_major_version == "8"
  tags: "apache_handlers"
