---
### トップレベルPlaybook ###
# 本ファイルは、個別のPlaybookの呼び出しを管理する。
# 個別のPlaybookはサーバの役割ごとに定義する。
# 1つの役割のサーバには、1つ以上複数のミドルウェアが動作する。
# 
# 記載例:
# - import_playbook: <個別Playbookファイル名>

- import_playbook: front.yml
- import_playbook: ap.yml
- import_playbook: db.yml
- import_playbook: docker.yml
