---
- name: "restart mariadb"
  systemd:
    name: mariadb.service
    state: restarted
  when: (ansible_distribution_major_version == "7") or
        (ansible_distribution_major_version == "8")
  tags: "restart_mariadb"
