---
### MariaDB用メインタスク
### 本ファイルは、別ファイルに定義されたタスクの呼び出しを行う。

#- name: "事前作業タスクのインクルード"
#  include_tasks: pre_tasks.yml
#  tags: "mariadb_pre_tasks"

- name: "パッケージ管理タスクのインクルード"
  include_tasks: packages.yml
  tags: "mariadb_packages"

- name: "OSグループ管理タスクのインクルード"
  include_tasks: groups.yml
  tags: "mariadb_groups"

- name: "OSユーザ管理タスクのインクルード"
  include_tasks: users.yml
  tags: "mariadb_users"

- name: "ディレクトリ管理タスクのインクルード"
  include_tasks: dirs.yml
  tags: "mariadb_dirs"

- name: "設定ファイル管理タスクのインクルード"
  include_tasks: conf_files.yml
  tags: "mariadb_conf_files"
#- name: "その他ファイル管理タスクのインクルード"
#  include_tasks: general_files.yml

#- name: "初期設定タスクのインクルード"
#  include_tasks: init_settings.yml

- name: "サービス起動管理タスクのインクルード"
  include_tasks: services.yml
  tags: "mariadb_services"

#- name: "事後作業タスクのインクルード"
#  include_tasks: post_tasks.yml
