---
### トップレベルTasksファイル ###
# 本ファイルでは、呼び出すTasksファイルの管理を行う。
# 作業単位でTasksファイルを分離し、必要な処理を呼び出す。
#
# 記載例:
# - import_tasks: <Tasksファイル名>

- import_tasks: configure_systemd_target.yml
- import_tasks: configure_selinux.yml
- import_tasks: configure_firewalld.yml
- import_tasks: configure_ipv6.yml
- import_tasks: configure_ntp.yml
- import_tasks: configure_dns.yml
