---
### トップレベルタスクファイル ###
# 本ファイルでは、呼び出すタスクファイルの管理を行う。
# 作業単位でタスクファイルを分離し、必要な処理を呼び出す。
#
# 記載例:
# - import_tasks: <Tasksファイル名>

- name: "デフォルトターゲット管理タスクの呼び出し"
  import_tasks: systemd_target.yml

- name: "SELinux状態管理タスクの呼び出し"
  import_tasks: selinux.yml

- name: "カーネルパラメータ管理タスクの呼び出し"
  import_tasks: kernel_parameter.yml

- name: "NTP設定管理タスクの呼び出し"
  import_tasks: ntp.yml

- name: "DNS設定管理タスクの呼び出し"
  import_tasks: dns.yml

- name: "SSH設定管理タスクの呼び出し"
  import_tasks: ssh.yml
