---
### 共通設定用NTP設定管理タスク
### 本ファイルは、NTP設定を管理する。

- name: cyronyd設定ファイルの配置
  template:
    src: etc_chrony.conf.j2
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: 0644
  notify: restart chronyd

