---
#- name: Check latest version.
#  shell: curl -s 'https://api.github.com/repos/docker/compose/releases/latest' |grep '"name":' | head -1 | sed -r 's/.*([0-9]+\.[0-9]+\.[0-9]+).*/\1/'
#  register: cmd_result

- name: Check latest version.
  uri:
    url: https://api.github.com/repos/docker/compose/releases/latest
    return_content: yes
  register: request_result

- name: Download compose.
  get_url:
    url: >-
      https://github.com/docker/compose/releases/download/{{ request_result.content | regex_search('"name":"[0-9]+\.[0-9]+\.[0-9]+"', multiline=True, ignorecase=True) | regex_search('[0-9]+\.[0-9]+\.[0-9]+') }}/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    owner: root
    group: root
    mode: '0755'

- name: Create symbolic link.
  file:
    src: /usr/local/bin/docker-compose
    dest: /usr/bin/docker-compose
    owner: root
    group: root
    mode: '0755'
    state: link
