---
### トップレベルTasksファイル ###
# 本ファイルでは、呼び出すTasksファイルの管理を行う。
# 作業単位でTasksファイルを分離し、必要な処理を呼び出す。
#
# 記載例:
# - import_tasks: <Tasksファイル名>
- import_tasks: install_docker.yml
- import_tasks: install_docker-compose.yml
